CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    nome VARCHAR(160) NOT NULL,
    cpf VARCHAR(11),
    email VARCHAR(200),
    telefone VARCHAR(30),
    cep VARCHAR(8),
    logradouro VARCHAR(200),
    numero VARCHAR(30),
    complemento VARCHAR(120),
    bairro VARCHAR(120),
    cidade VARCHAR(120),
    uf VARCHAR(2),
    estado_civil VARCHAR(40),
    profissao VARCHAR(120),
    versao BIGINT NOT NULL DEFAULT 0,
    criado_por_usuario_id BIGINT NOT NULL,
    atualizado_por_usuario_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_clientes_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_clientes_criado_por FOREIGN KEY (criado_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_clientes_atualizado_por FOREIGN KEY (atualizado_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT uk_clientes_empresa_cpf UNIQUE (empresa_id, cpf)
);

CREATE INDEX idx_clientes_empresa_nome ON clientes(empresa_id, nome);
CREATE INDEX idx_clientes_empresa_atualizado ON clientes(empresa_id, atualizado_em);

CREATE TABLE auditoria_operacional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    entidade VARCHAR(60) NOT NULL,
    entidade_id BIGINT NOT NULL,
    acao VARCHAR(40) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auditoria_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_auditoria_empresa_entidade ON auditoria_operacional(empresa_id, entidade, entidade_id, criado_em);
