CREATE TABLE empreendimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    nome VARCHAR(160) NOT NULL,
    spe VARCHAR(160),
    cnpj VARCHAR(14),
    area_total NUMERIC(19,4) NOT NULL DEFAULT 0,
    tipo VARCHAR(30) NOT NULL,
    unidades_previstas INTEGER NOT NULL DEFAULT 0,
    valor_total NUMERIC(19,2) NOT NULL DEFAULT 0,
    socio_pct NUMERIC(9,4) NOT NULL DEFAULT 0,
    empresa_pct NUMERIC(9,4) NOT NULL DEFAULT 0,
    corretor_pct NUMERIC(9,4) NOT NULL DEFAULT 0,
    aliquota_tributaria NUMERIC(9,4) NOT NULL DEFAULT 0,
    inadimplencia_json TEXT,
    observacoes TEXT,
    status VARCHAR(30) NOT NULL,
    versao BIGINT NOT NULL DEFAULT 0,
    criado_por_usuario_id BIGINT NOT NULL,
    atualizado_por_usuario_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_empreendimentos_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_empreendimentos_criado_por FOREIGN KEY (criado_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_empreendimentos_atualizado_por FOREIGN KEY (atualizado_por_usuario_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_empreendimentos_empresa ON empreendimentos(empresa_id, status, nome);
CREATE INDEX idx_empreendimentos_empresa_cnpj ON empreendimentos(empresa_id, cnpj);

CREATE TABLE quadras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    empreendimento_id BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    descricao TEXT,
    regras_json TEXT,
    versao BIGINT NOT NULL DEFAULT 0,
    criado_por_usuario_id BIGINT NOT NULL,
    atualizado_por_usuario_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_quadras_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_quadras_empreendimento FOREIGN KEY (empreendimento_id) REFERENCES empreendimentos(id),
    CONSTRAINT fk_quadras_criado_por FOREIGN KEY (criado_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_quadras_atualizado_por FOREIGN KEY (atualizado_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT uk_quadras_empresa_emp_nome UNIQUE (empresa_id, empreendimento_id, nome)
);

CREATE INDEX idx_quadras_empresa_emp ON quadras(empresa_id, empreendimento_id);

CREATE TABLE unidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    empreendimento_id BIGINT NOT NULL,
    quadra_id BIGINT,
    numero VARCHAR(80) NOT NULL,
    unidade VARCHAR(120) NOT NULL,
    unidade_tipo VARCHAR(30),
    descricao TEXT,
    area NUMERIC(19,4) NOT NULL DEFAULT 0,
    valor_venda NUMERIC(19,2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    regras_json TEXT,
    versao BIGINT NOT NULL DEFAULT 0,
    criado_por_usuario_id BIGINT NOT NULL,
    atualizado_por_usuario_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_unidades_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_unidades_empreendimento FOREIGN KEY (empreendimento_id) REFERENCES empreendimentos(id),
    CONSTRAINT fk_unidades_quadra FOREIGN KEY (quadra_id) REFERENCES quadras(id),
    CONSTRAINT fk_unidades_criado_por FOREIGN KEY (criado_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_unidades_atualizado_por FOREIGN KEY (atualizado_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT uk_unidades_empresa_emp_numero UNIQUE (empresa_id, empreendimento_id, numero)
);

CREATE INDEX idx_unidades_empresa_emp_status ON unidades(empresa_id, empreendimento_id, status);
CREATE INDEX idx_unidades_empresa_quadra ON unidades(empresa_id, quadra_id);

CREATE TABLE vendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    empreendimento_id BIGINT NOT NULL,
    unidade_id BIGINT NOT NULL,
    cliente_id BIGINT NOT NULL,
    valor_total NUMERIC(19,2) NOT NULL,
    data_contrato DATE NOT NULL,
    corretor_nome VARCHAR(160),
    corretor_pct NUMERIC(9,4) NOT NULL DEFAULT 0,
    observacoes TEXT,
    status VARCHAR(30) NOT NULL,
    regras_json TEXT NOT NULL,
    versao BIGINT NOT NULL DEFAULT 0,
    criado_por_usuario_id BIGINT NOT NULL,
    atualizado_por_usuario_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vendas_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_vendas_empreendimento FOREIGN KEY (empreendimento_id) REFERENCES empreendimentos(id),
    CONSTRAINT fk_vendas_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_vendas_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_vendas_criado_por FOREIGN KEY (criado_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_vendas_atualizado_por FOREIGN KEY (atualizado_por_usuario_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_vendas_empresa_unidade_status
    ON vendas(empresa_id, unidade_id, status);
CREATE INDEX idx_vendas_empresa_cliente ON vendas(empresa_id, cliente_id, data_contrato);
CREATE INDEX idx_vendas_empresa_emp ON vendas(empresa_id, empreendimento_id, data_contrato);

CREATE TABLE pagamento_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    venda_id BIGINT NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    descricao VARCHAR(240),
    valor NUMERIC(19,2) NOT NULL,
    parcelas INTEGER NOT NULL DEFAULT 1,
    primeiro_vencimento DATE NOT NULL,
    status VARCHAR(40) NOT NULL,
    observacoes TEXT,
    bem_json TEXT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pagamento_itens_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_pagamento_itens_venda FOREIGN KEY (venda_id) REFERENCES vendas(id)
);

CREATE INDEX idx_pagamento_itens_empresa_venda ON pagamento_itens(empresa_id, venda_id);

CREATE TABLE parcelas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    venda_id BIGINT NOT NULL,
    empreendimento_id BIGINT NOT NULL,
    unidade_id BIGINT NOT NULL,
    cliente_id BIGINT NOT NULL,
    origem_tipo VARCHAR(40) NOT NULL,
    origem_descricao VARCHAR(240),
    numero INTEGER NOT NULL,
    total_parcelas INTEGER NOT NULL,
    vencimento DATE NOT NULL,
    valor NUMERIC(19,2) NOT NULL,
    valor_pago NUMERIC(19,2) NOT NULL DEFAULT 0,
    data_pagamento DATE,
    status VARCHAR(30) NOT NULL,
    regras_inadimplencia_json TEXT,
    versao BIGINT NOT NULL DEFAULT 0,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_parcelas_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_parcelas_venda FOREIGN KEY (venda_id) REFERENCES vendas(id),
    CONSTRAINT fk_parcelas_empreendimento FOREIGN KEY (empreendimento_id) REFERENCES empreendimentos(id),
    CONSTRAINT fk_parcelas_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_parcelas_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);

CREATE INDEX idx_parcelas_empresa_status_vencimento ON parcelas(empresa_id, status, vencimento);
CREATE INDEX idx_parcelas_empresa_venda ON parcelas(empresa_id, venda_id);

CREATE TABLE movimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    parcela_id BIGINT NOT NULL,
    venda_id BIGINT NOT NULL,
    empreendimento_id BIGINT NOT NULL,
    unidade_id BIGINT NOT NULL,
    cliente_id BIGINT NOT NULL,
    corretor_nome VARCHAR(160),
    origem VARCHAR(40) NOT NULL,
    origem_descricao VARCHAR(240),
    data_movimento DATE NOT NULL,
    usuario_id BIGINT NOT NULL,
    valor_recebido NUMERIC(19,2) NOT NULL,
    imposto_reservado NUMERIC(19,2) NOT NULL,
    comissao_paga NUMERIC(19,2) NOT NULL,
    empresa_valor NUMERIC(19,2) NOT NULL,
    socio_valor NUMERIC(19,2) NOT NULL,
    aliquota_tributaria_aplicada NUMERIC(9,4),
    empresa_pct_aplicada NUMERIC(9,4),
    socio_pct_aplicada NUMERIC(9,4),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_movimentos_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_movimentos_parcela FOREIGN KEY (parcela_id) REFERENCES parcelas(id),
    CONSTRAINT fk_movimentos_venda FOREIGN KEY (venda_id) REFERENCES vendas(id),
    CONSTRAINT fk_movimentos_empreendimento FOREIGN KEY (empreendimento_id) REFERENCES empreendimentos(id),
    CONSTRAINT fk_movimentos_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_movimentos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_movimentos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_movimentos_empresa_data ON movimentos(empresa_id, data_movimento);
CREATE INDEX idx_movimentos_empresa_venda ON movimentos(empresa_id, venda_id);
CREATE INDEX idx_movimentos_empresa_parcela ON movimentos(empresa_id, parcela_id);

CREATE TABLE configuracoes_empresa (
    empresa_id BIGINT PRIMARY KEY,
    config_json TEXT NOT NULL,
    versao BIGINT NOT NULL DEFAULT 0,
    atualizado_por_usuario_id BIGINT NOT NULL,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_config_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_config_usuario FOREIGN KEY (atualizado_por_usuario_id) REFERENCES usuarios(id)
);
