package br.com.imobcontrol.tenant;

public enum PermissaoUsuario {
    CLIENTES_VISUALIZAR,
    CLIENTES_GERENCIAR,
    EMPREENDIMENTOS_VISUALIZAR,
    EMPREENDIMENTOS_GERENCIAR,
    VENDAS_VISUALIZAR,
    VENDAS_CRIAR,
    VENDAS_EDITAR,
    VENDAS_EXCLUIR,
    VENDAS_GERENCIAR,
    RECEBIMENTOS_VISUALIZAR,
    RECEBIMENTOS_REGISTRAR,
    RECEBIMENTOS_ESTORNAR,
    FINANCEIRO_VISUALIZAR,
    RELATORIOS_VISUALIZAR,
    CONFIGURACOES_GERENCIAR,
    EQUIPE_GERENCIAR
}
