/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecebedoresRouteImport } from './routes/recebedores'
import { Route as ParcelasRouteImport } from './routes/parcelas'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EmpreendimentosRouteImport } from './routes/empreendimentos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebedoresRoute = RecebedoresRouteImport.update({
  id: '/recebedores',
  path: '/recebedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelasRoute = ParcelasRouteImport.update({
  id: '/parcelas',
  path: '/parcelas',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpreendimentosRoute = EmpreendimentosRouteImport.update({
  id: '/empreendimentos',
  path: '/empreendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/empreendimentos': typeof EmpreendimentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/parcelas': typeof ParcelasRoute
  '/recebedores': typeof RecebedoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/empreendimentos': typeof EmpreendimentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/parcelas': typeof ParcelasRoute
  '/recebedores': typeof RecebedoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/empreendimentos': typeof EmpreendimentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/parcelas': typeof ParcelasRoute
  '/recebedores': typeof RecebedoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/empreendimentos'
    | '/financeiro'
    | '/parcelas'
    | '/recebedores'
    | '/relatorios'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/empreendimentos'
    | '/financeiro'
    | '/parcelas'
    | '/recebedores'
    | '/relatorios'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/empreendimentos'
    | '/financeiro'
    | '/parcelas'
    | '/recebedores'
    | '/relatorios'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EmpreendimentosRoute: typeof EmpreendimentosRoute
  FinanceiroRoute: typeof FinanceiroRoute
  ParcelasRoute: typeof ParcelasRoute
  RecebedoresRoute: typeof RecebedoresRoute
  RelatoriosRoute: typeof RelatoriosRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebedores': {
      id: '/recebedores'
      path: '/recebedores'
      fullPath: '/recebedores'
      preLoaderRoute: typeof RecebedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcelas': {
      id: '/parcelas'
      path: '/parcelas'
      fullPath: '/parcelas'
      preLoaderRoute: typeof ParcelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimentos': {
      id: '/empreendimentos'
      path: '/empreendimentos'
      fullPath: '/empreendimentos'
      preLoaderRoute: typeof EmpreendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EmpreendimentosRoute: EmpreendimentosRoute,
  FinanceiroRoute: FinanceiroRoute,
  ParcelasRoute: ParcelasRoute,
  RecebedoresRoute: RecebedoresRoute,
  RelatoriosRoute: RelatoriosRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
