/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as ParcelasRouteImport } from './routes/parcelas'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EmpreendimentosRouteImport } from './routes/empreendimentos'
import { Route as IndexRouteImport } from './routes/index'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelasRoute = ParcelasRouteImport.update({
  id: '/parcelas',
  path: '/parcelas',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpreendimentosRoute = EmpreendimentosRouteImport.update({
  id: '/empreendimentos',
  path: '/empreendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empreendimentos': typeof EmpreendimentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/parcelas': typeof ParcelasRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empreendimentos': typeof EmpreendimentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/parcelas': typeof ParcelasRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empreendimentos': typeof EmpreendimentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/parcelas': typeof ParcelasRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/empreendimentos' | '/financeiro' | '/parcelas' | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/empreendimentos' | '/financeiro' | '/parcelas' | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/empreendimentos'
    | '/financeiro'
    | '/parcelas'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpreendimentosRoute: typeof EmpreendimentosRoute
  FinanceiroRoute: typeof FinanceiroRoute
  ParcelasRoute: typeof ParcelasRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcelas': {
      id: '/parcelas'
      path: '/parcelas'
      fullPath: '/parcelas'
      preLoaderRoute: typeof ParcelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimentos': {
      id: '/empreendimentos'
      path: '/empreendimentos'
      fullPath: '/empreendimentos'
      preLoaderRoute: typeof EmpreendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpreendimentosRoute: EmpreendimentosRoute,
  FinanceiroRoute: FinanceiroRoute,
  ParcelasRoute: ParcelasRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
